# put real values below
spring.security.oauth2.client.registration.github.client-id=Iv23liowYsmRu5ehrBUt
spring.security.oauth2.client.registration.github.client-secret=9eba0a51409c4f6b4a6e3509afdb121b85c8397d