# put real values below
spring.security.oauth2.client.registration.github.client-id=Iv23liowYsmRu5ehrBUt
spring.security.oauth2.client.registration.github.client-secret=75fb25f6c394f1f8e3fffdb96770019b114b3c63